config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :posts
  resources :articles
  resources :about
  resources :feedbacks
  resources :welcome
  root 'welcome#index'

  
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
	validates_presence_of :fullname,:email,:body
    validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  	 @articles=Article.all.order("created_at ASC")
  	 @html_syntax="<!DOCTYPE html>
  	 <html>
  	 <head>
  	 <meta http-equiv='Content-Type' content='text/html; charset=utf-8'>
  	 <title>Hello HTML5 World</title>
  	 </head>
  	 <body>
  	 <h1>Hello HTML5</h1>
  	 <p>Welcome to the future of markup!</p>
  	 </body>
  	 </html>"      
  end

  def show
  	@article=Article.find(params[:id])
  end
   
  
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController

	def new
		@feedback=Feedback.new
	end

	def create
		@feedback=Feedback.new(feedback_params)
		if @feedback.save
			redirect_to feedbacks_path
		else
			render 'new'
		end
	end

	private
		def feedback_params
			params.require(:feedback).permit(:fullname,:email,:body)
		end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	 @posts=Post.all.order("created_at ASC")
  end

  def show
  	@post=Post.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@articles=Article.limit(3).all.order("created_at DESC")
 	@posts=Post.limit(3).all.order("created_at DESC")
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.haml
.container
 .row
  .col-xs-12.col-sm-6.col-md-8 
   %h1.first_header About Me
   %p.paragraph Hi I am Arjun Ghimire. I'm a designer & developer living in Butwal, Rupandehi. I have developed lot of websites from past 2 years. I have working experience with HTML 5, CSS 3, PHP, JavaScript, jQuery, Ajax, MySQL, SQLite and Ruby on rails. If you like to see my web project, you can find all my web project in my GitHub account.
  .col-xs-6.col-md-4 
   .panel.panel-info
    .panel-heading
     %h3.panel-title Follow Me 
    .panel-body 
     %p
     <a href="https://www.facebook.com/arjun.ghimire.1044" target="new">Facebook</a>
     %p
     <a href="https://github.com/Arjunghimire" target="new">Github</a>
     %p
     <a href="https://twitter.com/ArjunRazzGhimir" target="new">Twitter</a>

app/views/articles/index.html.haml
.container
 %h1.first_header Introduction of HTML
 %p.paragraph_html
  HTML5 specification not only embraces the past, by supporting traditional HTML- and XHTML-style syntax, but also adds a wide range of new featur Although HTML5 moves forward from HTML 4, it also is somewhat of a retreat and an admission that trying to get every Web developer on the Internet to write their markup properly is a futile effort, particularly because few Web developers are actually formally trained in the technology. 
  HTML5 tries to bring order to chaos by codifying common practices, embracing what is already implemented in browsers, and documenting how these user agents (browsers or other programs that consume Web pages) should deal with our imperfect markup.

  HTML5’s goals are grand. The specification is sprawling and often misunderstood.
  Given the confusion, the goals of this chapter are not only to summarize what is new about
  HTML5 and provide a roadmap to the element reference that follows, but to also expose
  some of the myths and misconceptions about this exciting new approach to markup.
 %hr
.container 
 %h2.second_header Hello World
 %p.paragraph_html
  The syntax of HTML5 should be mostly familiar. A simple
  HTML5 document looks like this:
  .example
   = (h @html_syntax).gsub("\n", "<br />").html_safe     
 %hr
 %h3.second_paragraph 
  All HTML Tags (
  = @articles.count
  )
 - @articles.each do |article|
  %h4.second_header= link_to article.title,article_path(article)
  %p.paragraph= article.body
  %hr

 

app/views/articles/show.html.haml
.container
 .main_contain_display
  %h4.second_header= @article.title
  %p.paragraph Description
  = @article.body

  %p.paragraph_example Example
  .example
   = (h @article.example).gsub("\n", "<br />").html_safe
  %p
  %hr
  =link_to "Back",articles_path,class:"btn btn-info"

app/views/feedbacks/_form.html.haml
= simple_form_for @feedback do |f|
 = f.input :fullname
 = f.input :email
 = f.input :body
 = f.submit

app/views/feedbacks/index.html.haml
.container
 %h2.second_header Thank you so much for your feedback. i will response soon !!!

app/views/feedbacks/new.html.haml
.container
 %h2.second_header Say anything to me 
 = render 'form'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Learncode
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default.navbar
      .container
        %ul.nav.navbar-nav
          %li= link_to "Learncode Academy", root_path
          %li= link_to "HTML", articles_path
          %li= link_to "CSS", posts_path
          %li= link_to "About Me",about_index_path
          %li= link_to "Feedback",new_feedback_path
  
      
  = yield
  %hr
  .container
    %p.paragraph &copy; Learncode Academy  2016

app/views/posts/index.html.haml
.container
 %h1.first_header Introduction of CSS
 %p.paragraph_html
  In the past, much of the visual formatting of Web pages was supplied by markup elements,squarely mixing the concepts of logical and physical markup into the mess that is classic HTML.
  Strict variants of (X)HTML deprecated the elements and attributes
  that focused on presentation, providing a clear distinction between the structure provided by markup and the look dictated by a style sheet written in Cascading Style Sheets (CSS)
  syntax. The distinct division of duties between markup and style can provide numerous
  production, maintenance, and even performance benefits, making it a far superior
  presentation solution to markup alone.
 %hr
 %h3.second_paragraph 
  All CSS Elements (
  = @posts.count
  )
 - @posts.each do |post|
  %h4.fourth_header= link_to post.title,post_path(post)
  %p.paragraph= post.body
  %hr

app/views/posts/show.html.haml
.container
 .main_contain_display
  %h4.fourth_header= @post.title
  %p.paragraph Description
  = @post.body

  %p.paragraph_example Syntax
  = @post.syntax
  %p.paragraph_example Example
  .example
   = simple_format(h @post.example)
  %p
  =link_to "Back",posts_path,class:"btn btn-info"

app/views/welcome/index.html.haml
.container
 .row
  .col-xs-12.col-sm-6.col-md-8 
   %h1.first_header Welcome Everybody
   %p.paragraph Hi everybody, I am Arjun Ghimire. I design this page for those who is new in web developing and want to develop static web page and blog. This site is really good for those who don't have any knowledge about web developing. You can learn ground level of HTML 5 and CSS 3 from this site. 
  .col-xs-6.col-md-4 
   .panel.panel-danger
    .panel-heading
     %h3.panel-title Latest Posts of HTML 5
    -@articles.each do |article|
     .panel-body= link_to article.title,article_path(article)
   .link_page= link_to "See more",articles_path
   %br/
   .panel.panel-success
    .panel-heading
     %h3.panel-title Latest Posts of CSS
    -@posts.each do |post|
     .panel-body= link_to post.title,post_path(post)
   .link_page= link_to "See more",posts_path
  